### ISSUE TITLE
Create one-step pipeline

### ISSUE THREAD

**Issue by angus-g** [COSIMA/mom6-regional-scripts#1]
The current workflow is constructed as a set of scripts that create different parts of the forcing set. This also means the configuration for the domain of interest is also split across these scripts. We made the observation that once we can point to a forcing dataset, and have both the ocean hgrid and topography, the entire workflow should be able to run automatically without further configuration. There may be some further configuration required for domains that are periodic, or don't need all four boundaries.

**Comment by ashjbarnes** [comment]
Although more work is to be done, I think this has been achieved through latest refactor of code into classes and methods
