### ISSUE TITLE
Runtime Error when running eac-003 on Setonix

### ISSUE THREAD

**Issue by reillyja** [COSIMA/mom6-regional-scripts#11]
I'm trying to figure out why a 30th degree config runs on Gadi fine, but when moved over to Setonix, after the required modifications to the relevant input files (i.e. new masktables etc.) produces an error: `NaN in input field of reproducing_sum(_3D)` . This happens at the initialisation of the first timestep. 

I've previously had this error pop up on Gadi, where @angus-g pointed out that the _FillValue for input fields needs to be a non-NaN value. This was fixed by encoding the velocities with `{_FillValue: netCDF4.default_fillvals["f4"]}`. 

@ChrisC28 has mentioned that Setonix, due to different architectures (Cray vs Intel?) might handle these fill-values and missing-values differently. I've compared these values for the new 30th-degree config, to those of an older 10th degree config that runs fine on Setonix and cannot see any difference. 

One key difference is how land-points are dealt with in the 3D input fields. Where, in the 10th degree config, these are masked out as NaNs (see below-left), in the 30th degree we've back-filled these to the closest right-hand-side ocean cell value (see below-right). (These snapshots are at 78m depth btw)
![eac-01-initial-temp_78m depth](https://user-images.githubusercontent.com/75762986/231631642-76f375b5-549e-491d-8095-c81a3417a393.png)
![eac-003-initial-temp_78mdepth](https://user-images.githubusercontent.com/75762986/231631810-feff7a4f-930c-4f54-b42e-6ad472480363.png)
@ashjbarnes, do you recall why we had to do the `bfill` for these initial conditions in the higher resolution setup?

Additionally, is there any way of determining which input field is triggering the error? @angus-g - any other ideas about what else I should check?

**Comment by angus-g** [comment]
Could you point me to your experiment directory on Setonix so I can have a poke around?

**Comment by reillyja** [comment]
Thanks Angus, the 30thdegree directory is: /home/jreilly/MOM6/eac-003-v3

The 10th degree directory using Chris' input files is: /home/jreilly/MOM6/mom6-eac

**Comment by angus-g** [comment]
Thanks. The other thing you can do is compile MOM6 with floating-point traps enabled (and optimisations disabled) -- this usually makes it pretty obvious where the error is coming from.

**Comment by angus-g** [comment]
I just ran this case with a more recent executable, and it seems to be having a lot of issues somewhere. There are a lot of warnings like this:
```
WARNING from PE    96: btstep: eta has dropped below bathyT:  -9.4789507570680467E+00 vs.  -9.3045969009399414E+00 at  -2.1495E+02 -3.8193E+01     63    404
```

And then there are grounding errors too:
```
MOM_forcing_type, forcing_SinglePointPrint: Called from applyBoundaryFluxesInOut (grounding)
MOM_forcing_type, forcing_SinglePointPrint: lon,lat =      -2.140E+02     -4.358E+01
MOM_forcing_type, forcing_SinglePointPrint: ustar =       1.261E-02
MOM_forcing_type, forcing_SinglePointPrint: buoy is not associated.
MOM_forcing_type, forcing_SinglePointPrint: sw =       7.668E+02
MOM_forcing_type, forcing_SinglePointPrint: sw_vis_dir =       2.185E+02
MOM_forcing_type, forcing_SinglePointPrint: sw_vis_dif =       2.185E+02
MOM_forcing_type, forcing_SinglePointPrint: sw_nir_dir =       1.649E+02
MOM_forcing_type, forcing_SinglePointPrint: sw_nir_dif =       1.649E+02
MOM_forcing_type, forcing_SinglePointPrint: lw =      -9.593E+01
MOM_forcing_type, forcing_SinglePointPrint: latent =      -1.214E+02
MOM_forcing_type, forcing_SinglePointPrint: latent_evap_diag =      -1.214E+02
MOM_forcing_type, forcing_SinglePointPrint: latent_fprec_diag =      -0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: latent_frunoff_diag =      -0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: sens =      -1.096E+01
MOM_forcing_type, forcing_SinglePointPrint: evap =      -4.857E-05
MOM_forcing_type, forcing_SinglePointPrint: lprec =       1.712E-09
MOM_forcing_type, forcing_SinglePointPrint: fprec =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: vprec =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: seaice_melt =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: seaice_melt_heat =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: p_surf =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: salt_flux =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: TKE_tidal =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: ustar_tidal =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: lrunoff =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: frunoff =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: heat_content_lrunoff =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: heat_content_frunoff =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: heat_content_lprec =       9.516E-05
MOM_forcing_type, forcing_SinglePointPrint: heat_content_fprec =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: heat_content_vprec =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: heat_content_cond =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: heat_content_massout =       0.000E+00
MOM_forcing_type, forcing_SinglePointPrint: heat_content_evap is not associated.
MOM_forcing_type, forcing_SinglePointPrint: heat_content_massout =      -2.682E+00
MOM_forcing_type, forcing_SinglePointPrint: heat_content_massin =       9.516E-05

WARNING from PE    33: MOM_diabatic_aux.F90, applyBoundaryFluxesInOut(): Mass created. x,y,dh=      -2.140E+02     -4.358E+01     -4.244E-24
```

And the actual fatal error occurs because it can't properly construct a grid for a column:
```
h<0 at k=           1 h_old=   1.9492467720577913E-008 wup=   0.0000000000000000      wdn=   4.2479979050540351E-003 dw_dz=  -4.2479979050540351E-003 h_new=  -4.2479784125863144E-003 h_err=   9.4324501655008388E-019

FATAL from PE    33: MOM_regridding: adjust_interface_motion() - implied h<0 is larger than roundoff!
```

I don't think the architecture would effect fill values or anything like that, but it's probably likely that you're running different versions of the code on different machines (unless you've been very careful to build the exact same version on both). I expect it's something to do with the different masking because of the different layouts. What was the layout you were originally using on Gadi?

**Comment by reillyja** [comment]
Are you referring to processor masking? For this particular setup, the Gadi processor mask was: `mask_table.96.20x62`

I'll have a bit more of a read into the other errors and things you've mentioned.

**Comment by reillyja** [comment]
Alrighty, so I've figured out that it must be the **deseas.f90** step that we've got in `mom6-regional-scripts.ipynb` that has been causing the issues on Setonix - namely the FATAL error: `NaN in input field of reproducing_sum(_3D)`. The model runs fine without this step included thankfully!

Not sure why this would be fine for Gadi and not Setonix - I might delve more into this or ask @ChrisC28 / Russ more about it.

**Comment by reillyja** [comment]
Thanks Micael. I'll give it a go now. The model was running fine up until around 80 days where it crashes with: `FATAL from PE   230: There were a total of         2 locations detected with extreme surface values` 

Surface Salinity exceeded 45 as shown in the figure below at a closed-off lake. Hopefully with the new `deseas` these will be fixed up I'd imagine?
![image](https://user-images.githubusercontent.com/75762986/233249447-94d8d3b3-06fe-4131-a467-0156a5da47d9.png)

**Comment by ashjbarnes** [comment]
Hey how'd we go with this? Any luck getting rid of these seas? You could try rename your holey topography topog_raw.nc and use the .bathymetry method in new pipeline, passing it the flag maketopog = False to stop it trying to run make_topog_parallel again. This uses a scipy function to fill in holes

**Comment by reillyja** [comment]
Thanks Ash - So it ended up being a pretty simple fix, just after using the `deseas.f90`, I had to change all NaNs (land points) to 0. Not sure if this was a step I missed in the notebook or is additional for Setonix but all good now!
