### ISSUE TITLE
Explain (via docs) or enhance (via type of args/kwargs) the input required for various methods

### ISSUE THREAD

**Issue by navidcy** [COSIMA/mom6-regional-scripts#146]
I was thinking we can enhance the args required by user-facing methods to minimize the chance that the users give the wrong form of inputs. We can do that by changing the type of the input args required _or_ by elaborating in the docstring and giving the users a few examples.

This was inspired by looking at the bathymetry method:

https://github.com/COSIMA/regional-mom6/blob/4931ce7aeb35d4358ebe5f5291a9a8c4d1ba449e/regional_mom6/regional_mom6.py#L895-L929

- First of all, `maketopog` should be `make_topography`; the former might require a comment to explain what it means, the latter is understood by just plain English.

- `bathy_path`  should be renamed to `bathymetry_path` and become a keyword argument.

- `varnames` is a dictionary, but we don't explain much... Could we simply ask for the user for the `longitude_coordinate_name`, `latitude_coordinate_name`, and `depth_coordinate_name` and then we use them under the hood inside `bathymetry` method to map these to the coordinate names that MOM6 expects? For example:

```python
def bathymetry( 
    self, 
    *,
    bathymetry_path, 
    longitude_coordinate_name,
    latitude_coordinate_name
    depth_coordinate_name 
    fill_channels=False, 
    minimum_layers=3, 
    make_topography=True, 
    positive_down=False, 
    chunks="auto", 
): 
```

These are some suggestions... Thoughts?

**Comment by ashjbarnes** [comment]
This has been addressed for bathymetry in PR #147

**Comment by navidcy** [comment]
For the bathymetry method, yes.
But the issue is valid for other methods. The bathymetry was just an example. We should do that to all user-facing methods.

**Comment by navidcy** [comment]
Let’s mot do that in this PR. We need to ensure the notebooks and tests are updated. It will be become.

**Comment by navidcy** [comment]
PR #147 is merged. I thing you pushed in a different branch.

**Comment by ashjbarnes** [comment]
Oops I mean #148

**Comment by navidcy** [comment]
I'm closing this as it is mostly done. We can open another specific issue for outstanding ambiguities.
