### ISSUE TITLE
key error in generating topo

### ISSUE THREAD

**Issue by AndyHoggANU** [COSIMA/mom6-regional-scripts#21]
I've made a start on testing out the demo script, but I get the following error when generating the topography:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /g/data/hh5/public/apps/miniconda3/envs/analysis3-22.10/lib/python3.9/site-packages/xarray/core/dataset.py:1347, in Dataset._construct_dataarray(self, name)
   1346 try:
-> 1347     variable = self._variables[name]
   1348 except KeyError:

KeyError: 'elevation'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
Cell In[8], line 1
----> 1 expt.bathymetry(
      2     '/g/data/ik11/inputs/GEBCO_2022/GEBCO_2022.nc',
      3     {"xh":"lon",
      4      "yh":"lat",
      5      "elevation":"elevation"}, ## Again this dictionary just maps mom6 variable names to what they are in your topog.
      6     )

File /home/149/ab8992/cosima_regional/mom6-regional-scripts/regional_library.py:702, in experiment.bathymetry(self, bathy_path, varnames, fill_channels, minimum_layers, maketopog)
    698 topog = xr.open_dataset(self.mom_input_dir + "topog_raw.nc", engine='netcdf4')
    700 ## Ensure correct encoding
    701 topog = xr.Dataset(
--> 702     {"depth":(["ny","nx"],topog[varnames["elevation"]].values)}
    703 )
    704 topog.attrs["depth"] = "meters"
    705 topog.attrs["standard_name"] = "topographic depth at T-cell centers"

File /g/data/hh5/public/apps/miniconda3/envs/analysis3-22.10/lib/python3.9/site-packages/xarray/core/dataset.py:1438, in Dataset.__getitem__(self, key)
   1436     return self.isel(**key)
   1437 if utils.hashable(key):
-> 1438     return self._construct_dataarray(key)
   1439 if utils.iterable_of_hashable(key):
   1440     return self._copy_listed(key)

File /g/data/hh5/public/apps/miniconda3/envs/analysis3-22.10/lib/python3.9/site-packages/xarray/core/dataset.py:1349, in Dataset._construct_dataarray(self, name)
   1347     variable = self._variables[name]
   1348 except KeyError:
-> 1349     _, name, variable = _get_virtual_variable(self._variables, name, self.dims)
   1351 needed_dims = set(variable.dims)
   1353 coords: dict[Hashable, Variable] = {}

File /g/data/hh5/public/apps/miniconda3/envs/analysis3-22.10/lib/python3.9/site-packages/xarray/core/dataset.py:185, in _get_virtual_variable(variables, key, dim_sizes)
    183 split_key = key.split(".", 1)
    184 if len(split_key) != 2:
--> 185     raise KeyError(key)
    187 ref_name, var_name = split_key
    188 ref_var = variables[ref_name]

KeyError: 'elevation'
```
Note that `bathy_original.nc` looks as it should, but `topog_raw.nc` doesn't get an elevation dimension ...

**Comment by ashjbarnes** [comment]
Looks like you’re calling my copy of the regional library on gadi. This is actually the one I’m actively developing on so you’re looking at the branch where I’ve replaced fre tools for bathymetry

This issue is because “mpirun ESMF_regrid” is intermittently failing and idk why! Currently working on it

To reduce confusion I’ll copy my development branch somewhere else and switch this back to master

**Comment by ashjbarnes** [comment]
On second thought I've just removed the `os.chdir` command from the preamble. The point of this was to make sure that my jupyter notebook was in the right directory to import the python libraries. The user will need to navigate to the directory where they cloned the repo and then it'll work. That way it's guaranteed that the 'demo notebook' and 'regional library' files are actually in sync with one another.

**Comment by AndyHoggANU** [comment]
OK, I've had another go with the latest code. Still can't get past the bathymetry step:

```
Error from pe 0: mpp_io(mpp_open): error in opening file ocean_mosaic.nc: No such file or directory
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
FRE TOOLS: make topog parallel

 CompletedProcess(args=['/g/data/v45/jr5971/FRE-NCtools/build3_up_MAXXGRID/tools/make_topog/make_topog_parallel', '--mosaic', 'ocean_mosaic.nc', '--topog_type', 'realistic', '--topog_file', 'bathy_original.nc', '--topog_field', 'elevation', '--scale_factor', '-1', '--output', 'topog_raw.nc'], returncode=255)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 expt.bathymetry(
      2     '/g/data/ik11/inputs/GEBCO_2022/GEBCO_2022.nc',
      3     {"xh":"lon",
      4      "yh":"lat",
      5      "elevation":"elevation"}, ## Again this dictionary just maps mom6 variable names to what they are in your topog.
      6     )

File /g/data/x77/amh157/mom6-regional-scripts/regional_library.py:699, in experiment.bathymetry(self, bathy_path, varnames, fill_channels, minimum_layers, maketopog)
    694 ## Remove inland lakes
    696 min_depth = self.vgrid.zi[minimum_layers]
--> 699 ocean_mask = topog.copy(deep = True).depth.where(topog.depth <= min_depth , 1)
    700 land_mask = np.abs(ocean_mask - 1)
    701 changed = True ## keeps track of whether solution has converged or not

File /g/data/hh5/public/apps/miniconda3/envs/analysis3-22.10/lib/python3.9/site-packages/xarray/core/common.py:268, in AttrAccessMixin.__getattr__(self, name)
    266         with suppress(KeyError):
    267             return source[name]
--> 268 raise AttributeError(
    269     f"{type(self).__name__!r} object has no attribute {name!r}"
    270 )

AttributeError: 'Dataset' object has no attribute 'depth'
```

It's possible that I should be

**Comment by reillyja** [comment]
Again, not sure if i'm on the same commit - but I had to run the `expt._old_make_hgrid()` to first generate the ocean mosaic, and other grid files. Then running `expt.bathymetry` worked for me.

**Comment by ashjbarnes** [comment]
@AndyHoggANU how big is your test domain, and how many cores are you running the notebook on?

If you're on the current master branch, it still calls the FRE tools to make the bathymetry. It looks like it's throwing an error code for you

In my dev branch (which I'm really hoping to merge later today) I've replaced FRE tools for bathy and hgrid generation. For big domains / small memory jobs, FRE tools make topography will hang or fail. Then, you'll get the key error because topog hasn't been generated properly (in new version I raise a more useful error message when topog generation fails)

**Comment by AndyHoggANU** [comment]
Domain is 14° x 20°, 0.05° resolution (so only 280 x 400). Is that considered large?

Am testing out John's solution ...

**Comment by ashjbarnes** [comment]
If you're still working on it this arvo I'd recommend switching to my [dev branch](https://github.com/COSIMA/mom6-regional-scripts/tree/rewrite-bathymetry) 

In this one the model runs but was crashing on one of my test domains so I'm still troubleshooting that

**Comment by ashjbarnes** [comment]
Try the newdemo.ipynb which will replace the demo on master when I figure out whether it's causing the model to crash, or simply my timestep or some other thing

**Comment by navidcy** [comment]
Is this resolved? I see that the `rewrite-bathymetry` branch is now merged to `master`...

**Comment by ashjbarnes** [comment]
Yeah this should be fixed. I was going to leave it open pending someone else testing the new demo notebook. I spent my afternoon testing it before merging but chances are it will break as soon as someone else looks at it...

**Comment by navidcy** [comment]
@AndyHoggANU could you give it a go once more using `master`?

**Comment by AndyHoggANU** [comment]
Happy.
