### ISSUE TITLE
Base resolution set by topography.

### ISSUE THREAD

**Issue by ChrisC28** [COSIMA/mom6-regional-scripts#7]
At present, the regional config scripts essentially take an h_grid as an input. It would be good to roll this process into the workflow so that the user specifies the latitudinal and longitudinal extent of the domain, its topoology (ie. pan-Antarctic or 4 sided cookie cutter) and resolution. 

In one of my many discussions with @russfiedler , we thought that specifying horizontal grid points using some underlying "base resolution" that is specified by the bathymetry could be a good approach to ensuring that regional configurations have more-or-less comparable grids. For example, if the bathymetry is generated by GEBCO2022 (with 15 arcsecond horizontal grid spacing=15/3600), then a regional grid would be set by an integer multiple sub-sampling the bathymetric _grid_. 

Does this sound like a viable approach?

**Comment by ashjbarnes** [comment]
Sounds great, would love to learn how this works! The next part of my project requires automatic re-scaling of topography so I'll be working on this soon too  (hopefully in Hobart next month)

**Comment by ChrisC28** [comment]
Note that the "base grid" could be anything. Bathymetry could be a (possibly nice) to set that, but it's not 100% neccesary.

**Comment by ChrisC28** [comment]
Found an issue with this idea: the resolution of GEBCO is too large and breaks make_hgrid. For now, I'll work with a separate base grid and map the bathymetry to that grid. However, a better solution is desireable.

**Comment by russfiedler** [comment]
@ChrisC28 there is an MPI version of `make_topog` called `make_topog_parallel`. I built a version in 2019 by the looks.

**Comment by aekiss** [comment]
I don't think GEBCO would be a suitable base grid. GEBCO is on a non-Mercator grid (uniform latitude spacing) but we'd normally use a Mercator grid in the model to keep the cells roughly square, and something very different at the north pole.

**Comment by ashjbarnes** [comment]
I think to keep things modular we leave the generation of the hgrid up to the user. Like generate mercator hgrid by default, but allow user to overwrite this and give whatever they want. Then, everything else gets hurled at the hgrid (including bathymetry). That's how the .bathymetry method works currently
